name: Train ML Model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: sentiment-env

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow==2.19.0

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run .